import { createFileRoute, notFound } from "@tanstack/react-router";
import { DocsLayout } from "fumadocs-ui/layouts/docs";
import browserCollections from "collections/browser";
import { DocsBody, DocsDescription, DocsPage, DocsTitle } from "fumadocs-ui/layouts/docs/page";
import { deserializePageTree } from "fumadocs-core/source/client";
import { Suspense } from "react";
import { getMDXComponents } from "@/components/mdx";
// @ts-expect-error — virtual module generated by docsDataPlugin
import { pathMap, pageTree as staticPageTree } from "virtual:docs-data";

export const Route = createFileRoute("/docs/$")({
  component: Page,
  loader: async ({ params }) => {
    const slugKey = params._splat ?? "";
    const path = (pathMap as Record<string, string>)[slugKey];
    if (!path) {
      throw notFound();
    }
    await clientLoader.preload(path);
    return { path };
  },
});

const mdxComponents = getMDXComponents();

const clientLoader = browserCollections.docs.createClientLoader({
  component({ frontmatter, default: MDX, toc }) {
    return (
      <DocsPage toc={toc}>
        <DocsTitle>{frontmatter.title}</DocsTitle>
        <DocsDescription>{frontmatter.description}</DocsDescription>
        <DocsBody>
          <MDX components={mdxComponents} />
        </DocsBody>
      </DocsPage>
    );
  },
});

const tree = deserializePageTree(staticPageTree);

function Page() {
  const { path } = Route.useLoaderData();

  return (
    <DocsLayout tree={tree} nav={{ title: "Kural" }} githubUrl="https://github.com/razyones/kural">
      <Suspense>{clientLoader.useContent(path)}</Suspense>
    </DocsLayout>
  );
}
