import { createFileRoute, notFound } from "@tanstack/react-router";
import { DocsLayout } from "fumadocs-ui/layouts/docs";
import { createServerFn } from "@tanstack/react-start";
import { source } from "@/lib/source";
import browserCollections from "collections/browser";
import { DocsBody, DocsDescription, DocsPage, DocsTitle } from "fumadocs-ui/layouts/docs/page";
import { useFumadocsLoader } from "fumadocs-core/source/client";
import { Suspense } from "react";
import { getMDXComponents } from "@/components/mdx";
// @ts-expect-error — virtual module generated by docsDataPlugin
import { pathMap } from "virtual:docs-data";

export const Route = createFileRoute("/docs/$")({
  component: Page,
  loader: async ({ params }) => {
    const slugs = params._splat?.split("/") ?? [];

    // Try server function first (works during SSR / prerender).
    // Falls back to client-side path resolution for static hosting
    // where the server endpoint doesn't exist.
    try {
      const data = await getPageData({ data: slugs });
      await clientLoader.preload(data.path);
      return data;
    } catch {
      const slugKey = slugs.join("/");
      const path = (pathMap as Record<string, string>)[slugKey];
      if (!path) {
        throw notFound();
      }
      await clientLoader.preload(path);
      return { path, pageTree: null };
    }
  },
});

let cachedPageTree: Awaited<ReturnType<typeof source.serializePageTree>> | null = null;

async function getSerializedPageTree() {
  cachedPageTree ??= await source.serializePageTree(source.getPageTree());
  return cachedPageTree;
}

const getPageData = createServerFn({
  method: "GET",
})
  .inputValidator((slugs: string[]) => slugs)
  .handler(async ({ data: slugs }) => {
    const page = source.getPage(slugs);
    if (!page) {
      throw notFound();
    }

    return {
      path: page.path,
      pageTree: await getSerializedPageTree(),
    };
  });

const mdxComponents = getMDXComponents();

const clientLoader = browserCollections.docs.createClientLoader({
  component({ frontmatter, default: MDX, toc }) {
    return (
      <DocsPage toc={toc}>
        <DocsTitle>{frontmatter.title}</DocsTitle>
        <DocsDescription>{frontmatter.description}</DocsDescription>
        <DocsBody>
          <MDX components={mdxComponents} />
        </DocsBody>
      </DocsPage>
    );
  },
});

function Page() {
  const data = useFumadocsLoader(Route.useLoaderData());

  return (
    <DocsLayout
      tree={data.pageTree ?? {}}
      nav={{ title: "Kural" }}
      githubUrl="https://github.com/user/kural"
    >
      <Suspense>{clientLoader.useContent(data.path)}</Suspense>
    </DocsLayout>
  );
}
