import { createFileRoute, notFound } from "@tanstack/react-router";
import { DocsLayout } from "fumadocs-ui/layouts/docs";
import browserCollections from "collections/browser";
import {
  DocsBody,
  DocsDescription,
  DocsPage,
  DocsTitle,
  MarkdownCopyButton,
  ViewOptionsPopover,
} from "fumadocs-ui/layouts/docs/page";
import { deserializePageTree } from "fumadocs-core/source/client";
import { Suspense } from "react";
import { NavLogo } from "@/components/nav-logo";
import { getMDXComponents } from "@/components/mdx";
import config from "../../../docs.config";
// @ts-expect-error — virtual module generated by docsDataPlugin
import { pageMeta, pathMap, pageTree as staticPageTree } from "virtual:docs-data";

const base = import.meta.env.BASE_URL ?? "/";
const siteUrl = new URL(base, config.url).href.replace(/\/$/, "");
const baseHref = base.replace(/\/$/, "");
const REPO_URL = "https://github.com/razyones/kural";
const REPO_BRANCH = "alpha";

type PageMeta = Record<string, { title: string; description: string }>;

export const Route = createFileRoute("/docs/$")({
  component: Page,
  loader: async ({ params }) => {
    const slugKey = params._splat ?? "";
    const path = (pathMap as Record<string, string>)[slugKey];
    if (!path) {
      throw notFound();
    }
    const meta = (pageMeta as PageMeta)[slugKey];
    await clientLoader.preload(path);
    const slug = slugKey === "" ? "" : `/${slugKey}`;
    const markdownUrl = slugKey === "" ? `${baseHref}/docs.mdx` : `${baseHref}/docs/${slugKey}.mdx`;
    const githubUrl = `${REPO_URL}/blob/${REPO_BRANCH}/docs/${path}`;
    return {
      path,
      slug,
      markdownUrl,
      githubUrl,
      title: meta?.title ?? config.name,
      description: meta?.description ?? "",
    };
  },
  head: ({ loaderData }) => {
    const title =
      loaderData?.title && loaderData.title !== config.name
        ? `${loaderData.title} - ${config.name}`
        : config.name;
    const description = loaderData?.description || config.description;
    const url = `${siteUrl}/docs${loaderData?.slug ?? ""}`;
    return {
      meta: [
        { title },
        { name: "description", content: description },
        { property: "og:title", content: title },
        { property: "og:description", content: description },
        { property: "og:type", content: "article" },
        { property: "og:url", content: url },
        { name: "twitter:title", content: title },
        { name: "twitter:description", content: description },
      ],
      links: [{ rel: "canonical", href: url }],
    };
  },
});

const mdxComponents = getMDXComponents();

const clientLoader = browserCollections.docs.createClientLoader({
  component({ frontmatter, default: MDX, toc }) {
    const { markdownUrl, githubUrl } = Route.useLoaderData();
    return (
      <DocsPage toc={toc}>
        <DocsTitle>{frontmatter.title}</DocsTitle>
        <DocsDescription>{frontmatter.description}</DocsDescription>
        <div className="flex flex-row flex-wrap items-center gap-2 -mt-6 mb-6 pb-6 border-b border-fd-border">
          <MarkdownCopyButton markdownUrl={markdownUrl} />
          <ViewOptionsPopover markdownUrl={markdownUrl} githubUrl={githubUrl} />
        </div>
        <DocsBody>
          <MDX components={mdxComponents} />
        </DocsBody>
      </DocsPage>
    );
  },
});

const tree = deserializePageTree(staticPageTree);

function Page() {
  const { path } = Route.useLoaderData();

  return (
    <DocsLayout
      tree={tree}
      nav={{ title: <NavLogo /> }}
      githubUrl="https://github.com/razyones/kural"
    >
      <Suspense>{clientLoader.useContent(path)}</Suspense>
    </DocsLayout>
  );
}
