import { create, insert, search } from "@orama/orama";
// @ts-expect-error — virtual module generated by docsDataPlugin
import { searchEntries } from "virtual:docs-data";

type Entry = { title: string; description: string; url: string; content: string };

let dbPromise: Promise<Awaited<ReturnType<typeof create>>> | null = null;

async function buildDB() {
  const db = await create({
    schema: {
      url: "string",
      title: "string",
      description: "string",
      content: "string",
    },
  });
  for (const entry of searchEntries as Entry[]) {
    await insert(db, entry);
  }
  return db;
}

export async function searchDocs(query: string) {
  dbPromise ??= buildDB();
  const db = await dbPromise;
  const results = await search(db, {
    term: query,
    tolerance: 1,
    boost: { title: 2 },
  });
  return results.hits.map((hit) => ({
    type: "page" as const,
    content: hit.document.title,
    id: hit.document.url,
    url: hit.document.url,
  }));
}
