import { create, insert, search } from "@orama/orama";
import { createContentHighlighter } from "fumadocs-core/search";
// @ts-expect-error — virtual module generated by docsDataPlugin
import { searchEntries } from "virtual:docs-data";

interface StructuredData {
  headings: Array<{ id: string; content: string }>;
  contents: Array<{ heading?: string; content: string }>;
}

interface Entry {
  title: string;
  description: string;
  url: string;
  breadcrumbs?: string[];
  structuredData: StructuredData;
}

let dbPromise: Promise<Awaited<ReturnType<typeof create>>> | null = null;

/** Stores page-level metadata for enriching search results. */
const pageMeta = new Map<string, { breadcrumbs?: string[]; title: string }>();

async function buildDB() {
  const db = await create({
    schema: {
      page_id: "string",
      type: "string",
      url: "string",
      content: "string",
    },
  });

  for (const entry of searchEntries as Entry[]) {
    pageMeta.set(entry.url, {
      breadcrumbs: entry.breadcrumbs,
      title: entry.title,
    });

    // Page entry
    await insert(db, {
      page_id: entry.url,
      type: "page",
      url: entry.url,
      content: entry.title,
    });

    // Description entry
    if (entry.description) {
      await insert(db, {
        page_id: entry.url,
        type: "text",
        url: entry.url,
        content: entry.description,
      });
    }

    // Heading entries
    for (const heading of entry.structuredData.headings) {
      await insert(db, {
        page_id: entry.url,
        type: "heading",
        url: `${entry.url}#${heading.id}`,
        content: heading.content,
      });
    }

    // Content entries — skip very short snippets
    for (const section of entry.structuredData.contents) {
      if (!section.content || section.content.length < 30) continue;
      await insert(db, {
        page_id: entry.url,
        type: "text",
        url: section.heading ? `${entry.url}#${section.heading}` : entry.url,
        content: section.content,
      });
    }
  }

  return db;
}

export async function searchDocs(query: string) {
  dbPromise ??= buildDB();
  const db = await dbPromise;
  const highlighter = createContentHighlighter(query);
  const results = await search(db, {
    term: query,
    tolerance: 1,
    limit: 8,
    boost: { content: 2 },
  });

  return results.hits.map((hit) => {
    const type = hit.document.type as "page" | "heading" | "text";
    const meta = pageMeta.get(hit.document.page_id);
    return {
      type,
      content: highlighter.highlightMarkdown(hit.document.content),
      // Only page entries get breadcrumbs — headings/text inherit context
      breadcrumbs: type === "page" ? meta?.breadcrumbs : undefined,
      id: hit.document.url,
      url: hit.document.url,
    };
  });
}
